version: '3.3'

services:
  app:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app

  db:
    image: mysql:8
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--sql-mode=ALLOW_INVALID_DATES',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
      - db-persistence:/var/lib/mysql
    environment:
      MYSQL_DATABASE: personnel_development
      MYSQL_ROOT_PASSWORD: pwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8081:80"

volumes:
  db-persistence:
