version: '3.3'

services:
  app:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/personnel

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
      - db-persistence:/var/lib/mysql
    environment:
      MYSQL_DATABASE: personnel_development
      MYSQL_ROOT_PASSWORD: pwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8081:80"

volumes:
  db-persistence:
