version: '3.3'

services:
  app:
    depends_on:
      - db
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

  db:
    image: mysql:5.5
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
      - db-persistence:/var/lib/mysql
    environment:
      MYSQL_DATABASE: personnel_development
      MYSQL_ROOT_PASSWORD: pwd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8081:80"

volumes:
  db-persistence:
