version: '3.3'

services:
  app:
    depends_on:
      - db
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

  db:
    image: postgres
    volumes:
      - db-persistence:/var/lib/postgresql/data

volumes:
  db-persistence:
