version: '3'
services:
  db:
    image: postgres
    ports:
      - '5433:5432'

  server:
    depends_on:
      - db
    ports:
      - '8080:8080'
    image: node:9-alpine
    user: node
    working_dir: /home/node/app
    command: npm run dev
    volumes:
      - ./:/home/node/app
    environment:
      DATABASE_URL: postgres://postgres:pwd@db:5432/postgres
      NODE_ENV: development
      PORT: 8080
