production:
  discourse:
    base_url:
      internal: https://forums.29th.org
      external: https://forums.29th.org
    api_key: <%= ENV.fetch('DISCOURSE_API_KEY') %>
    webhooks_secret: <%= ENV.fetch('DISCOURSE_WEBHOOKS_SECRET') %>
    cookie_name: <%= ENV.fetch('DISCOURSE_COOKIE_NAME') %>
    secret_key: <%= ENV.fetch('DISCOURSE_SECRET_KEY') %>
  personnel_v2_app:
    base_url:
      internal: https://personnel.29th.org
      external: https://personnel.29th.org
  personnel_v2_api:
    base_url:
      internal: https://api.29th.org
      external: https://api.29th.org
    api_key: <%= ENV.fetch('V2_ADMIN_API_KEY') %>
  vanilla:
    base_url:
      internal: https://vanilla.29th.org
      external: https://vanilla.29th.org
    api_key: <%= ENV.fetch('VANILLA_API_KEY') %>
  storage:
    endpoint: <%= ENV.fetch('STORAGE_ENDPOINT') %>
    bucket: <%= ENV.fetch('STORAGE_BUCKET') %>
    region: <%= ENV.fetch('STORAGE_REGION') %>
    access_key_id: <%= ENV.fetch('STORAGE_ACCESS_KEY_ID') %>
    secret_access_key: <%= ENV.fetch('STORAGE_SECRET_ACCESS_KEY') %>
    public_host: <%= ENV.fetch('STORAGE_PUBLIC_HOST', 'https://uploads.29th.org') %>

