name: Deploy

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [master]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: personnel
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
